# Generated by Django 5.2.2 on 2025-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_contact_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
