# Generated by Django 5.2.2 on 2025-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
